# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zowU-ttD7IAGVbQIsVv_SWl4qxLJwRfu
"""

import numpy as np
from statistics import mode
from scipy import stats

# 예제 데이터 집합: 학생들의 시험 점수
exam_scores = [82, 90, 76, 92, 88, 79, 95, 87, 90, 76, 92, 90, 85, 78, 85]

# 평균 계산
mean_score = np.mean(exam_scores)

# 중앙값 계산
median_score = np.median(exam_scores)

# 최빈값 계산 (방법 1: statistics.mode) → 단일 최빈값만 반환
mode_score = mode(exam_scores)

# 최빈값 계산 (방법 2: scipy.stats.mode) → 여러 최빈값 처리 가능
mode_result = stats.mode(exam_scores, keepdims=True)

print("평균:", mean_score)
print("중앙값:", median_score)
print("최빈값 (statistics):", mode_score)
print("최빈값 (scipy):", mode_result.mode[0], "빈도수:", mode_result.count[0])

import numpy as np
from scipy.stats import variation

# 예제 데이터 집합
data = [1, 2, 2, 3, 4, 5, 5, 5, 6]

# 범위 계산
data_range = np.max(data) - np.min(data)

# 분산 계산
variance = np.var(data, ddof=0)          # 모집단 분산
sample_variance = np.var(data, ddof=1)   # 표본 분산

# 표준편차 계산
std_deviation = np.std(data, ddof=0)          # 모집단 표준편차
sample_std_deviation = np.std(data, ddof=1)   # 표본 표준편차

# 변동계수 (Coefficient of Variation, CV)
cv = variation(data)   # 표본/모집단 모두 가능, 평균 대비 표준편차 비율

print("범위:", data_range)
print("모집단 분산:", variance)
print("표본 분산:", sample_variance)
print("모집단 표준편차:", std_deviation)
print("표본 표준편차:", sample_std_deviation)
print("변동계수(CV):", cv)

import matplotlib.pyplot as plt

data = [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20]

# 수평 상자그림 + 이상치 빨간색
plt.boxplot(data, vert=False, flierprops=dict(marker='o', markerfacecolor='red', markersize=8))

plt.title("Horizontal Boxplot of Data")
plt.xlabel("Values")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 예제 데이터 집합
data = [1, 2, 2, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 7, 7, 7,
        8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 12,
        13, 13, 13, 13, 13, 13, 14, 15, 15, 16, 16, 17, 18,
        19, 19, 20, 20, 20]

# 히스토그램 구간(bin) 정의 (0~20까지 정수 간격)
bins = np.arange(0, max(data) + 1.5) - 0.5

# 히스토그램 생성
plt.hist(data, bins=bins, edgecolor='black')

# 제목과 축 레이블 추가
plt.title('Histogram of Data')
plt.xlabel('Value')
plt.ylabel('Frequency')

# 그래프 표시
plt.show()

