# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVrrFkbs2a5heDvvIxfhRGCE62nBuQXW
"""

import random

trials = 10000       # 총 시행 횟수
even_rolls_count = 0 # 짝수 눈이 나온 횟수

for _ in range(trials):
    roll = random.randint(1, 6)  # 주사위 눈금 (1~6)
    if roll % 2 == 0:            # 짝수인지 판별
        even_rolls_count += 1

# 짝수가 나올 확률 계산
probability_even = even_rolls_count / trials
print("짝수가 나올 확률:", probability_even)

S = {1, 2, 3, 4, 5, 6}
A = {1, 2}
B = {1, 3, 5}

# 합집합: A ∪ B
union_AB = A.union(B)

# 교집합: A ∩ B
intersection_AB = A.intersection(B)

# 여집합: A' (A의 여집합)
complement_A = S.difference(A)

# 여집합: B' (B의 여집합)
complement_B = S.difference(B)

# 결과 출력
print("A ∪ B:", union_AB)
print("A ∩ B:", intersection_AB)
print("A' :", complement_A)
print("B' :", complement_B)

# 각 색의 공의 개수
red_balls = 2
blue_balls = 3
green_balls = 5

# 특정 색(빨간색) 공이 나올 경우의 수
favorable_outcomes = red_balls

# 상자 안의 모든 가능한 결과의 수
total_outcomes = red_balls + blue_balls + green_balls

# 확률 계산
probability = favorable_outcomes / total_outcomes
print("빨간색 공이 나올 확률:", probability)

import numpy as np
import matplotlib.pyplot as plt

# 주사위 던지기 시뮬레이션 횟수 설정: 1,000회
n_throws_short = 1000

# 주사위 던지기 결과 생성 (1~6 사이의 무작위 정수, 1,000회)
throws_short = np.random.randint(1, 7, size=n_throws_short)

# 4가 나온 횟수를 기록할 배열 (초기값 0으로 채움)
fours_count_short = np.zeros(n_throws_short)

# 각 던지기마다 4가 나온 횟수 누적
for i in range(1, n_throws_short):
    fours_count_short[i] = fours_count_short[i - 1] + (throws_short[i] == 4)

# 각 시점에서의 확률 계산
probabilities_short = fours_count_short / np.arange(1, n_throws_short + 1)

# 결과 그래프로 표시
plt.figure(figsize=(10, 6))
plt.plot(probabilities_short, label='Simulated Probability')

# 이론적 확률(1/6 ≈ 0.1667) 표시
plt.axhline(y=1/6, color='r', linestyle='--', label='Theoretical Probability (1/6)')

# 그래프 설정
plt.xlabel('Number of Throws')
plt.ylabel('Probability of Throwing a 4')
plt.title('Probability of Throwing a 4 Converging to 1/6 (1,000 Throws)')
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 주머니 안의 공 정의 (3 빨강, 4 파랑)
bag = ['R'] * 3 + ['B'] * 4

# 시뮬레이션 횟수
n_picks = 10000

# 복원 추출 시뮬레이션
picks = np.random.choice(bag, size=n_picks, replace=True)

# 각 뽑기마다 빨간색 공을 뽑은 누적 횟수 기록
red_count_cumulative = np.cumsum(picks == 'R')

# 각 시점에서의 실험적 확률 계산
probabilities_red_cumulative = red_count_cumulative / np.arange(1, n_picks + 1)

# 결과 그래프로 표시
plt.figure(figsize=(10, 6))
plt.plot(probabilities_red_cumulative, label='Simulated Probability of Red')

# 이론적 확률 3/7 ≈ 0.4286 표시
plt.axhline(y=3/7, color='r', linestyle='--', label='Theoretical Probability (3/7)')

# 그래프 설정
plt.xlabel('Number of Picks')
plt.ylabel('Probability of Picking a Red Ball')
plt.title('Probability of Picking a Red Ball Converging to 3/7')
plt.legend()
plt.grid(True)
plt.show()

