# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RARU-vekky5HKMIuAmwdQp-Y6cYUk4ri
"""

a = [2, 3, 4, 5, 6]
b = []

for _ in range(len(a)):
    b.append(a.pop())

print(b)