# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VN274aPjfFX6fcNk9a9OGU9pR0am8WLb
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([78.4, 78.6, 78.5, 78.9, 79.4, 78.6, 78.6])  # 7개 맞춤

plt.scatter(x, y, color="r")   # 빨간 점으로 출력
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([78.4, 78.6, 78.5, 78.9, 78.2, 79.4, 78.6])  # 7개 데이터

plt.plot(x, y, color="r")  # 빨간 선 그래프
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([78.4, 78.6, 78.5, 78.9, 78.2, 79.4, 78.6])

plt.plot(x, y, "ro-", linewidth=1)  # 빨간 선 + 점
plt.grid(True)                      # 격자 표시
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-5, 5, 100)   # -5부터 5까지 100개 점
y1 = x**2                     # 첫 번째 곡선 (빨간 실선)
y2 = (x-2)**2                 # 두 번째 곡선 (검은 점선)

plt.plot(x, y1, 'r')          # 빨간 실선
plt.plot(x, y2, 'k--')        # 검은 점선
plt.grid(True)                # 격자 표시
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-5, 5, 100)
y1 = 2 * x         # 빨간 선
y2 = 5 * x         # 검은 점선

plt.plot(x, y1, 'r', label='y1 값')     # 빨간 실선
plt.plot(x, y2, 'k--', label='y2 값')   # 검은 점선

plt.title("그래프 제목")   # 그래프 제목
plt.xlabel("X-축")        # x축 라벨
plt.ylabel("Y-축")        # y축 라벨
plt.legend()              # 범례 표시
plt.grid(True)            # 격자 표시

plt.show()

