# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189Zm0y77PJBtzO5540CzECdkMX1ypnxL
"""

print("김시우")
print("20")

